version: '3'
services:
  node-app:
    container_name: node-app
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_IP=mongo
      - MONGO_PORT=27017
    depends_on: 
      - mongo    
  mongo:
    image: mongo
    container_name: node-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gil
      - MONGO_INITDB_ROOT_PASSWORD=admin123    
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-db: