version: "3"
services:
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=gil
      - MONGO_PASSWORD=admin123
      - SESSION_SECRET=mysecret
    command: ["npm", "run", "dev"]

  