version: '3'
services:
  nginx:
      container_name: node-nginx
      image: nginx:stable-alpine
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro    
  node-app:
    container_name: node-app
    build: .  
    environment:
      - PORT=3000
      - MONGO_IP=mongo
      - MONGO_PORT=27017
    depends_on: 
      - mongo    
  mongo:
    image: mongo
    container_name: node-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gil
      - MONGO_INITDB_ROOT_PASSWORD=admin123    
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
  redis:
    container_name: node-redis
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
      
volumes:
  mongo-db: