version: '3'
services: 
  node-app:  
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=3000
    # env_file:
    #   - ./.env
    image: gilmartmd/node-app-image
    container_name: node-app
